# Generated by Django 2.1 on 2023-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_company',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
