# Generated by Django 2.1 on 2023-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230314_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_company',
            field=models.CharField(max_length=100),
        ),
    ]
