# Generated by Django 2.1 on 2023-01-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230114_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
    ]
