# Generated by Django 2.1 on 2023-01-15 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20230114_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=15)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('whatsapp', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], default='other', max_length=6)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=300, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumersCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=50)),
                ('cod_card', models.CharField(max_length=5)),
                ('expiration_date', models.DateField()),
                ('flag_card', models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('hipercard', 'Hipercarde'), ('banricompras', 'Banricompras'), ('elo', 'Elo'), ('alelo', 'Alelo'), ('america_express', 'American express')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumers',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_consumer', to='register.ConsumersCards'),
        ),
    ]
