# Generated by Django 2.1 on 2023-03-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20230314_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='pix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txid', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=8)),
                ('time', models.CharField(max_length=25)),
                ('payer_pix_key', models.CharField(max_length=45)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Consumers')),
                ('recive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='return_pix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.CharField(max_length=40)),
                ('rtrid', models.CharField(max_length=40)),
                ('values', models.CharField(max_length=8)),
                ('status', models.BooleanField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Consumers')),
                ('recive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pix',
            name='return_pix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.return_pix'),
        ),
    ]
