# Generated by Django 2.1 on 2023-03-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20230320_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='return_pix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Return_pix'),
        ),
    ]
