# Generated by Django 2.1 on 2023-01-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20230115_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('savings_account', models.BooleanField()),
                ('company_bank', models.CharField(max_length=100)),
                ('agency_bank', models.CharField(max_length=8)),
                ('bank_account', models.CharField(max_length=8)),
                ('account_digit', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_name', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_owner', models.CharField(max_length=150)),
                ('email_owner', models.EmailField(max_length=254)),
                ('phone_owner', models.CharField(max_length=12)),
                ('cep', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf_owner', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('public_name', models.CharField(max_length=200)),
                ('business_phone', models.CharField(max_length=12)),
                ('plan', models.BooleanField(choices=[('plan_basic', 'Plano Basico'), ('plan_premium', 'Plano Completo')])),
                ('business_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_payment', to='register.BusinessTransfer')),
                ('business_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_business', to='register.BusinessSpecialty')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uf', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.State'),
        ),
        migrations.AddField(
            model_name='businesstransfer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_company', to='register.Company'),
        ),
    ]
