# Generated by Django 2.1 on 2023-03-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20230320_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pix',
            old_name='recive',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='return_pix',
            old_name='recive',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='pix',
            name='payer_pix_key',
        ),
        migrations.AlterField(
            model_name='pix',
            name='return_pix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Return_pix'),
        ),
    ]
