# Generated by Django 2.1 on 2023-01-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20230115_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_bank',
        ),
    ]
