# Generated by Django 2.1 on 2023-01-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20230115_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(max_length=50)),
                ('sub_specialty', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='businessspecialty',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='business_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_company', to='register.CompanySpecialty'),
        ),
        migrations.DeleteModel(
            name='BusinessSpecialty',
        ),
    ]
