# Generated by Django 2.1 on 2023-01-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20230116_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('plan_basic', 'Plano Basico'), ('plan_premium', 'Plano Completo')], max_length=10),
        ),
    ]
