# Generated by Django 2.1 on 2023-01-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_avalable',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='business_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_company', to='register.CompanySpecialty'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_categori',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
