# Generated by Django 2.1 on 2023-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20230117_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_categori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
