# Generated by Django 2.1 on 2023-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20230117_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
