# Generated by Django 2.1 on 2023-01-20 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20230120_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consumer_name', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
