# Generated by Django 2.1 on 2023-01-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20230120_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
