# Generated by Django 2.1 on 2023-01-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_log_permission_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permicted', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('administrator', 'Administrativo'), ('clerk', 'Atendimento')], default='clerk', max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Company')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.CompanyPermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='is_avalable',
            field=models.BooleanField(default=False),
        ),
    ]
