# Generated by Django 2.1 on 2023-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_auto_20230122_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categori', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_categori',
        ),
        migrations.AddField(
            model_name='products',
            name='product_categori',
            field=models.ManyToManyField(related_name='categori_product', to='register.ProductCategori'),
        ),
    ]
