# Generated by Django 2.1 on 2023-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20230122_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategori',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='categori',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_categori',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(related_name='category_product', to='register.ProductCategory'),
        ),
    ]
