# Generated by Django 2.1 on 2023-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20230122_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
