# Generated by Django 2.1 on 2023-01-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20230122_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='category_product', to='register.ProductCategory'),
        ),
    ]
