# Generated by Django 2.1 on 2023-01-24 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20230122_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_productcategory', to='register.ProductCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='register.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ptoductcategory_subcategory', to='register.SubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_product', to='register.SubCategory'),
        ),
    ]
