# Generated by Django 2.1 on 2023-01-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20230124_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptoductcategory_subcategory', to='register.SubCategory'),
        ),
    ]
