# Generated by Django 2.1 on 2023-01-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_auto_20230124_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_sub_category',
        ),
    ]
