# Generated by Django 2.1 on 2023-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_purchase_shopping_cart_whishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishes',
            name='name_whishes_list',
            field=models.CharField(default='PDesejos', max_length=50),
            preserve_default=False,
        ),
    ]
