# Generated by Django 2.1 on 2023-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_productsrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsrating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
