# Generated by Django 2.1 on 2023-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_auto_20230211_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
