# Generated by Django 2.1 on 2023-02-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_consumers_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_sales', to='register.Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sale', to='register.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='businesstransfer',
            name='pix_key',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesstransfer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_company', to='register.Company'),
        ),
    ]
