# Generated by Django 2.1 on 2023-02-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_consumers_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
