# Generated by Django 2.1 on 2023-02-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_auto_20230212_2316'),
        ('register', '0036_company_picture_url'),
    ]

    operations = [
    ]
