# Generated by Django 2.1 on 2023-02-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_auto_20230213_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_token',
        ),
    ]
