# Generated by Django 2.1 on 2023-02-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_remove_user_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='companypermission',
            name='level_permissions',
            field=models.CharField(choices=[('Master', 'Completo'), ('reports', 'Relatorios'), ('payments', 'Pagamentos'), ('deliveries', 'Entregas'), ('basic', 'Basico')], default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companypermission',
            name='permicted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_company', to='register.Permission'),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
