# Generated by Django 2.1 on 2023-02-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0040_auto_20230216_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypermission',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to='register.Company'),
            preserve_default=False,
        ),
    ]
